import type { Config } from 'tailwindcss'

export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'on-secondary-fixed': '#1a1b1f',
        primary: '#0058bc',
        'glass-fill-light': 'rgba(255, 255, 255, 0.20)',
        'primary-container': '#0070eb',
        'glass-border': 'rgba(255, 255, 255, 0.25)',
        outline: '#717786',
        'color-teal-dark': '#64D2FF',
        'on-surface-variant': '#414755',
        'color-green-dark': '#30D158',
        'color-green': '#34C759',
        'bg-primary': '#FFFFFF',
        'primary-fixed-dim': '#adc6ff',
        'error-container': '#ffdad6',
        'color-red': '#FF3B30',
        tertiary: '#9e3d00',
        'surface-tint': '#005bc1',
        'secondary-container': '#e0dfe4',
        'on-primary-fixed': '#001a41',
        'surface-container-low': '#f1f3fe',
        'on-secondary': '#ffffff',
        'tertiary-fixed': '#ffdbcc',
        'color-red-dark': '#FF453A',
        'on-tertiary-container': '#fffbff',
        'bg-nav-dark': 'rgba(28, 28, 30, 0.86)',
        surface: '#f9f9ff',
        'on-error': '#ffffff',
        'on-tertiary': '#ffffff',
        'on-tertiary-fixed-variant': '#7c2e00',
        'surface-variant': '#e0e2ed',
        'color-orange': '#FF9500',
        'on-secondary-container': '#626267',
        'on-primary-container': '#fefcff',
        'on-tertiary-fixed': '#351000',
        'secondary-fixed-dim': '#c6c6cb',
        'on-secondary-fixed-variant': '#46464b',
        'surface-bright': '#f9f9ff',
        'label-secondary': 'rgba(60, 60, 67, 0.60)',
        'tertiary-container': '#c64f00',
        'surface-dim': '#d8d9e5',
        'inverse-surface': '#2d3039',
        'on-surface': '#181c23',
        'inverse-on-surface': '#eef0fc',
        background: '#FFFFFF',
        'color-orange-dark': '#FF9F0A',
        'color-blue-dark': '#0A84FF',
        'label-secondary-dark': 'rgba(235, 235, 245, 0.60)',
        'color-purple-dark': '#BF5AF2',
        'surface-container-lowest': '#ffffff',
        'label-primary-dark': '#FFFFFF',
        'tertiary-fixed-dim': '#ffb595',
        'bg-primary-dark': '#000000',
        'on-error-container': '#93000a',
        'color-purple': '#AF52DE',
        error: '#ba1a1a',
        'surface-container-highest': '#e0e2ed',
        'surface-container-high': '#e6e8f3',
        'surface-container': '#ecedf9',
        'color-teal': '#59ADC4',
        'inverse-primary': '#adc6ff',
        'glass-fill-dark': 'rgba(255, 255, 255, 0.08)',
        'on-primary-fixed-variant': '#004493',
        'label-primary': '#000000',
        'secondary-fixed': '#e3e2e7',
        'on-primary': '#ffffff',
        'glass-shadow': 'rgba(31, 38, 135, 0.35)',
        'bg-nav-light': 'rgba(255, 255, 255, 0.92)',
        secondary: '#5d5e63',
        'outline-variant': '#c1c6d7',
        'primary-fixed': '#d8e2ff',
        'on-background': '#000000',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
        '2xl': '1rem',
        '3xl': '1.5rem',
      },
      spacing: {
        'space-1': '4px',
        'space-2': '8px',
        'space-3': '12px',
        'space-4': '16px',
        'space-5': '20px',
        'space-6': '24px',
        'space-8': '32px',
        'space-10': '40px',
      },
      fontFamily: {
        'large-title': ['Inter', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        'caption-2': ['Inter', 'sans-serif'],
        footnote: ['Inter', 'sans-serif'],
        'title-1': ['Inter', 'sans-serif'],
        subheadline: ['Inter', 'sans-serif'],
        'title-2': ['Inter', 'sans-serif'],
        headline: ['Inter', 'sans-serif'],
        callout: ['Inter', 'sans-serif'],
        'caption-1': ['Inter', 'sans-serif'],
        'title-3': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'large-title': ['34px', { lineHeight: '41px', fontWeight: '400' }],
        body: ['17px', { lineHeight: '22px', fontWeight: '400' }],
        'caption-2': ['11px', { lineHeight: '13px', fontWeight: '400' }],
        footnote: ['13px', { lineHeight: '18px', fontWeight: '400' }],
        'title-1': ['28px', { lineHeight: '34px', fontWeight: '400' }],
        subheadline: ['15px', { lineHeight: '20px', fontWeight: '400' }],
        'title-2': ['22px', { lineHeight: '28px', fontWeight: '400' }],
        headline: ['17px', { lineHeight: '22px', fontWeight: '600' }],
        callout: ['16px', { lineHeight: '21px', fontWeight: '400' }],
        'caption-1': ['12px', { lineHeight: '16px', fontWeight: '400' }],
        'title-3': ['20px', { lineHeight: '25px', fontWeight: '400' }],
      },
      boxShadow: {
        glass: '0 8px 32px 0 rgba(31, 38, 135, 0.35)',
      },
    },
  },
  plugins: [],
} satisfies Config
